### ISSUE TITLE
Polygonizing inaccurate and changes sprite texture

### ISSUE THREAD

**Issue by JarLowrey** [timoschwarzer/polygonizer-gd-addon#2]
![before](https://user-images.githubusercontent.com/7429786/30087835-ef0b5078-9270-11e7-8173-c52881a9d2a1.PNG)

![after](https://user-images.githubusercontent.com/7429786/30087834-ef035724-9270-11e7-80b9-85487af81c71.PNG)

**Comment by timoschwarzer** [comment]
Unfortunately, this behavior is unavoidable.

### Workarounds:
- Make sure the edge pixels of your asset are 100% transparent
- OR: Set the resolution and margin to 0.
